apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mastodon.fullname" . }}-env
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
data:
  {{- include "mastodon.env" . | indent 2 }}
